language: node_js
node_js:
  - node
addons:
  ssh_known_hosts: s9.mydevil.net
before_deploy:
  - openssl aes-256-cbc -K $encrypted_503344c8b3cd_key -iv $encrypted_503344c8b3cd_iv
    -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
