language: node_js
node_js:
  - node
addons:
  ssh_known_hosts: $deploy_host
install:
  - npm run init:install:ci
script:
  - npm run test
  - npm run build
before_deploy:
  - openssl aes-256-cbc -K $encrypted_503344c8b3cd_key -iv $encrypted_503344c8b3cd_iv
    -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script:
    - scp -rp $TRAVIS_BUILD_DIR/build/* $deploy_user@$deploy_host:$deploy_path/$TRAVIS_BUILD_ID
    - ssh $deploy_user@$deploy_host 'cd $deploy_path && rm -rf old.build && mv public_nodejs old.build && mv $TRAVIS_BUILD_ID public_nodejs && cp env/.env public_nodejs && cd public_nodejs && npm ci && $deploy_restart_server'
  on:
    tags: true
